emit:
  - "@typespec/http-client-java"
options:
  "@typespec/http-client-java":
    emitter-output-dir: "{project-root}/tsp-output"
    flavor: "azurev2"
    dev-options:
      generate-code-model: false
      loglevel: info
      debug: false
