emit:
  - "@typespec/http-client-java"
options:
  "@typespec/http-client-java":
    emitter-output-dir: "{project-root}/../../../../../azure-sdk-for-java/sdk/appconfiguration/azure-data-appconfiguration-v2"
    namespace: "com.azure.v2.data.appconfiguration"
    flavor: "azurev2"
    dev-options:
      generate-code-model: true
      loglevel: info
      debug: false
