emit:
  - 'java-spring'

# Example options this emitter can take
options:
  java-spring:
    # The spring version used in generated code
    springVersion: 3.3.3
    # The java version declared in maven config for compiling
    javaVersion: 8
    # The package all java code is emitted to
    package: io.typespec.generated
    # The maven groupId for the generated project
    groupId: io.typespec
    # The maven artifactId for the generated project
    artifactId: demo-service
    # The maven version for the generated project
    version: 1.0.0
    # The path to customization file
    # extension: file://C:/Users/srnagar/home/code/typespec/packages/java-spring/tsp-output/dist/src/extension.js
